settings:
  title: 'Nathan Service Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: alist-nathan21hz-cc
    name: Alist
    description: 'File share service' # default=empty
    url: 'https://alist.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: bus-nathan21hz-cc
    name: Bus
    description: 'Convenient bus status page' # default=empty
    url: 'https://bus.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: gallery-nathan21hz-cc
    name: Gallery
    description: 'Photography gallery' # default=empty
    url: 'https://gallery.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: gpt-nathan21hz-cc
    name: ChatGPT
    description: 'Self-hosted ChatGPT webui' # default=empty
    url: 'https://gpt.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: jellyfin-nathan21hz-cc
    name: Jellyfin
    description: 'Self-hosted video service' # default=empty
    url: 'https://jellyfin.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: aria2-ququ-nathan21hz-cc
    name: Aria2-Ququ
    description: 'Remote download service for ququ' # default=empty
    url: 'https://aria2-ququ.nathan21hz.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 401 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
